name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "xsqian" --password-stdin
        docker image build -t xsqian/gitops:hellov1.1 .
        docker push xsqian/gitops:hellov1.1
